const cvs=document.getElementById('stars');const ctx=cvs.getContext('2d',{alpha:true});let W,H,DPR,stars=[],t=0,tiltX=0,tiltY=0;
const PUMP_LINK='https://pump.fun/';const TG_LINK='https://t.me/';const X_LINK='https://x.com/MimiMoonsSOL?t=gKUXygbh4UNRWcvmZHsF5Q&s=09';
[['pumpLink',PUMP_LINK],['xLink',X_LINK],['tgLink',TG_LINK],['buyTop',PUMP_LINK],['buyMain',PUMP_LINK],['joinTg',TG_LINK]].forEach(([i,u])=>{const e=document.getElementById(i);if(e)e.href=u;});
function resize(){DPR=Math.max(1,window.devicePixelRatio||1);W=cvs.width=Math.floor(window.innerWidth*DPR);H=cvs.height=Math.floor(window.innerHeight*DPR);cvs.style.width=window.innerWidth+'px';cvs.style.height=window.innerHeight+'px';const n=Math.min(800,Math.max(160,Math.floor((W*H)/24000)));stars=Array.from({length:n},()=>({x:Math.random()*W,y:Math.random()*H,z:Math.random()*0.9+0.1,r:Math.random()*1.4+0.5,spd:Math.random()*0.6+0.2}))}
window.addEventListener('resize',resize);resize();
function mv(e){const p=e.touches?e.touches[0]:e;const cx=p.clientX-window.innerWidth/2;const cy=p.clientY-window.innerHeight/2;tiltX=cx/(window.innerWidth/2);tiltY=cy/(window.innerHeight/2)}
window.addEventListener('mousemove',mv,{passive:true});window.addEventListener('touchmove',mv,{passive:true});
function draw(){t+=0.016;ctx.clearRect(0,0,W,H);const g=ctx.createRadialGradient(W*0.65,H*0.15,0,W*0.65,H*0.15,Math.max(W,H)*0.95);g.addColorStop(0,'rgba(18,30,70,.45)');g.addColorStop(1,'rgba(10,14,36,1)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(const s of stars){const px=W/2+(s.x-W/2)+tiltX*(1.2-s.z)*24;let py=s.y+Math.sin((t+s.x*0.0008))*8+tiltY*(1.2-s.z)*24+t*s.spd*16;py=(py%H+H)%H;ctx.globalAlpha=0.65+(1-s.z)*0.45;ctx.beginPath();ctx.arc(px,py,s.r*s.z*DPR,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()}requestAnimationFrame(draw)}draw();
const copyBtn=document.getElementById('copyBtn'),contractText=document.getElementById('contractText'),copiedToast=document.getElementById('copiedToast');copyBtn?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(contractText.textContent.trim());if(copiedToast){copiedToast.style.opacity=1;setTimeout(()=>copiedToast.style.opacity=0,1200)}}catch(e){alert('Copy failed')}});
